"""Read agent-flow's orchestration state file and derive a run outcome.

Per the "Subagents LIE" principle, the model's final prose is never trusted
as the source of truth for whether a run succeeded. The orchestration state
file (`.claude/orchestration.local.md`), written through
`scripts/update-orchestration-state.sh`, is authoritative: `active`,
`current_phase`, per-phase `gates.*.status`, and `report_requested` decide
the outcome. The `<orchestration-complete>TASK VERIFIED</orchestration-complete>`
sentinel in the final text is corroborating evidence only.

The frontmatter is machine-generated by agent-flow's own scripts with a
fixed, two-space-indented shape, so a small stdlib parser is sufficient —
this package deliberately avoids a YAML dependency, matching the
stdlib-only convention of `scripts/analyze/`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

STATE_FILE_RELPATH = Path(".claude") / "orchestration.local.md"
COMPLETION_SENTINEL = "<orchestration-complete>TASK VERIFIED</orchestration-complete>"

GATE_ORDER = ("exploration", "planning", "implementation", "review", "verification")


def _coerce_scalar(raw: str) -> Any:
    value = raw.strip()
    if value.startswith('"') and value.endswith('"') and len(value) >= 2:
        return value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    if value == "true":
        return True
    if value == "false":
        return False
    if value in ("", "~", "null"):
        return None
    try:
        return int(value)
    except ValueError:
        return value


def parse_frontmatter(text: str) -> dict[str, Any]:
    """Parse the state file's YAML frontmatter (indentation-based, 2 spaces)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    root: dict[str, Any] = {}
    # Stack of (indent, mapping) so nested blocks attach to the right parent.
    stack: list[tuple[int, dict[str, Any]]] = [(-1, root)]
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if ":" not in stripped:
            continue
        key, _, raw_value = stripped.partition(":")
        key = key.strip()
        while stack and indent <= stack[-1][0]:
            stack.pop()
        parent = stack[-1][1] if stack else root
        if raw_value.strip() == "":
            child: dict[str, Any] = {}
            parent[key] = child
            stack.append((indent, child))
        else:
            parent[key] = _coerce_scalar(raw_value)
    return root


@dataclass
class OrchestrationState:
    exists: bool
    active: bool = False
    current_phase: str = ""
    iteration: int = 0
    max_iterations: int = 0
    task: str = ""
    task_complexity: str = "unclassified"
    report_requested: bool = False
    gates: dict[str, dict[str, Any]] = field(default_factory=dict)
    raw: dict[str, Any] = field(default_factory=dict)

    def gate_status(self, gate: str) -> str:
        return str(self.gates.get(gate, {}).get("status", "pending"))

    def gate_message(self, gate: str) -> str:
        return str(self.gates.get(gate, {}).get("message", ""))

    @classmethod
    def load(cls, workspace: Path) -> "OrchestrationState":
        path = Path(workspace) / STATE_FILE_RELPATH
        if not path.is_file():
            return cls(exists=False)
        data = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        gates_raw = data.get("gates", {})
        gates = {k: v for k, v in gates_raw.items() if isinstance(v, dict)} if isinstance(gates_raw, dict) else {}
        return cls(
            exists=True,
            active=bool(data.get("active", False)),
            current_phase=str(data.get("current_phase", "")),
            iteration=int(data.get("iteration", 0) or 0),
            max_iterations=int(data.get("max_iterations", 0) or 0),
            task=str(data.get("task", "")),
            task_complexity=str(data.get("task_complexity", "unclassified")),
            report_requested=bool(data.get("report_requested", False)),
            gates=gates,
            raw=data,
        )


@dataclass
class Outcome:
    status: str  # a ResultStatus value
    reason: str
    resumable: bool
    detail: dict[str, Any] = field(default_factory=dict)


def derive_outcome(
    state: OrchestrationState,
    *,
    final_text: str = "",
    pending_question: bool = False,
    run_error: str | None = None,
) -> Outcome:
    """Map orchestration state (+ how the SDK run ended) to a lifecycle outcome.

    Precedence: an escalated question beats everything (the run was
    deliberately interrupted to ask it); then hard run errors; then the
    state file's own verdict.
    """
    from agentflow_headless.result import ResultStatus  # local to avoid cycle

    if pending_question:
        return Outcome(
            status=ResultStatus.NEEDS_INPUT,
            reason="orchestration escalated a question to the caller",
            resumable=True,
        )

    gate_detail = {g: state.gate_status(g) for g in GATE_ORDER} if state.exists else {}
    detail: dict[str, Any] = {
        "current_phase": state.current_phase,
        "iteration": state.iteration,
        "gates": gate_detail,
        "task_complexity": state.task_complexity,
        "completion_sentinel_seen": COMPLETION_SENTINEL in final_text,
    }

    if run_error is not None:
        return Outcome(
            status=ResultStatus.FAILED,
            reason=run_error,
            resumable=state.exists,
            detail=detail,
        )

    if not state.exists:
        return Outcome(
            status=ResultStatus.FAILED,
            reason="orchestration state file was never created; the run did not initialize",
            resumable=False,
            detail=detail,
        )

    verification = state.gate_status("verification")

    if not state.active:
        if verification == "passed":
            return Outcome(
                status=ResultStatus.COMPLETED,
                reason="verification gate passed and orchestration marked complete",
                resumable=False,
                detail=detail,
            )
        if state.report_requested or state.task_complexity in ("research", "exploratory"):
            # Research short-circuit: these runs legitimately end without the
            # implementation/verification gates; the report is the deliverable.
            return Outcome(
                status=ResultStatus.COMPLETED,
                reason="research/report run completed (no implementation phases expected)",
                resumable=False,
                detail=detail,
            )
        return Outcome(
            status=ResultStatus.FAILED,
            reason=(
                "orchestration ended without a passed verification gate "
                f"(verification={verification}, phase={state.current_phase})"
            ),
            resumable=False,
            detail=detail,
        )

    # active: true — the run stopped mid-orchestration (turn budget, wall-clock
    # budget, or transport interruption). Session state persists on disk, so
    # this is resumable.
    return Outcome(
        status=ResultStatus.FAILED,
        reason=(
            "run ended while orchestration was still active "
            f"(phase={state.current_phase}, iteration={state.iteration}/{state.max_iterations}); "
            "the session can be resumed"
        ),
        resumable=True,
        detail=detail,
    )
