#!/bin/bash
# ensure-gitignore.sh — idempotently inject agent-flow artifact patterns into
# the working project's .gitignore.
#
# Usage: ensure-gitignore.sh [--project-dir <dir>]
#
# Guards:
#   AGENT_FLOW_NO_GITIGNORE=1  → skip silently
#   Project is agent-flow itself (.claude-plugin/plugin.json name == agent-flow) → skip

set -euo pipefail

TEMP_FILE=""
cleanup() {
  [[ -n "$TEMP_FILE" && -f "$TEMP_FILE" ]] && rm -f "$TEMP_FILE"
  return 0
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
PROJECT_DIR=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --project-dir)
      if [[ -z "${2:-}" ]]; then
        echo "Error: --project-dir requires an argument" >&2
        exit 1
      fi
      PROJECT_DIR="$2"
      shift 2
      ;;
    *)
      echo "Error: Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Resolve project directory
# ---------------------------------------------------------------------------
if [[ -z "$PROJECT_DIR" ]]; then
  PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
fi
TARGET="$PROJECT_DIR/.gitignore"

# ---------------------------------------------------------------------------
# Guard: opt-out env var
# ---------------------------------------------------------------------------
if [[ -n "${AGENT_FLOW_NO_GITIGNORE:-}" ]]; then
  exit 0
fi

# ---------------------------------------------------------------------------
# Guard: don't touch the agent-flow plugin repo itself
# ---------------------------------------------------------------------------
PLUGIN_JSON="$PROJECT_DIR/.claude-plugin/plugin.json"
if [[ -f "$PLUGIN_JSON" ]]; then
  IS_AF=false
  if command -v jq &>/dev/null; then
    PLUGIN_NAME=$(jq -r '.name // empty' "$PLUGIN_JSON" 2>/dev/null || true)
    [[ "$PLUGIN_NAME" == "agent-flow" ]] && IS_AF=true
  else
    grep -q '"name"[[:space:]]*:[[:space:]]*"agent-flow"' "$PLUGIN_JSON" 2>/dev/null && IS_AF=true
  fi
  if [[ "$IS_AF" == true ]]; then
    exit 0
  fi
fi

# ---------------------------------------------------------------------------
# Canonical managed block definition
# ---------------------------------------------------------------------------
START_MARKER="# >>> agent-flow managed (do not edit) >>>"
END_MARKER="# <<< agent-flow managed <<<"

read -r -d '' MANAGED_BLOCK << 'BLOCK_EOF' || true
# >>> agent-flow managed (do not edit) >>>
# Generated by agent-flow commands (orchestrate / deep-dive / explain / graphify).
# Remove this whole block to opt out, or set AGENT_FLOW_NO_GITIGNORE=1.
.claude/*.local.*
.claude/codex/
.claude/explain-briefs/
.claude/observability/
graphify-out/
explain-out/
# <<< agent-flow managed <<<
BLOCK_EOF

# ---------------------------------------------------------------------------
# Case 1: .gitignore does not exist — create it fresh
# ---------------------------------------------------------------------------
if [[ ! -f "$TARGET" ]]; then
  TEMP_FILE="${TARGET}.tmp.$$"
  printf '%s\n' "$MANAGED_BLOCK" > "$TEMP_FILE"
  mv "$TEMP_FILE" "$TARGET"
  exit 0
fi

# ---------------------------------------------------------------------------
# Case 2: .gitignore exists — strip old block (if valid), append fresh block
# ---------------------------------------------------------------------------

# Detect CRLF in existing file
USE_CRLF=false
if grep -qP '\r' "$TARGET" 2>/dev/null || grep -q $'\r' "$TARGET" 2>/dev/null; then
  USE_CRLF=true
fi

# Only strip if BOTH markers are present (avoids eating content on malformed file)
START_COUNT=$(grep -cF "$START_MARKER" "$TARGET" 2>/dev/null || true)
END_COUNT=$(grep -cF "$END_MARKER" "$TARGET" 2>/dev/null || true)

TEMP_FILE="${TARGET}.tmp.$$"

if [[ "$START_COUNT" -ge 1 && "$END_COUNT" -ge 1 ]]; then
  # Strip the managed block using awk.
  # Strip \r from each line before comparing (handles CRLF files); print $0
  # to preserve original bytes in surviving user lines.
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    { line=$0; gsub(/\r/, "", line) }
    line == start { skip=1; next }
    skip && line == end { skip=0; next }
    !skip { print }
  ' "$TARGET" > "$TEMP_FILE"
else
  # Malformed or no block — pass through unchanged
  cp "$TARGET" "$TEMP_FILE"
fi

# Ensure surviving content ends with exactly one newline before appending block.
# -s guarantees non-empty; just check whether the last byte is a newline.
if [[ -s "$TEMP_FILE" ]]; then
  LAST_BYTE=$(tail -c 1 "$TEMP_FILE" | od -An -tx1 | tr -d ' \n')
  if [[ "$LAST_BYTE" != "0a" && "$LAST_BYTE" != "0d" ]]; then
    printf '\n' >> "$TEMP_FILE"
  fi
fi

# Append the managed block (with CRLF conversion if needed).
# On CRLF files, convert every line ending to \r\n so the entire block is
# consistently CRLF (no mixed bare-\n inside the block).
if [[ "$USE_CRLF" == true ]]; then
  printf '%s\n' "$MANAGED_BLOCK" | awk '{printf "%s\r\n", $0}' >> "$TEMP_FILE"
else
  printf '%s\n' "$MANAGED_BLOCK" >> "$TEMP_FILE"
fi

# Idempotency short-circuit: if the result is identical, skip the mv
if cmp -s "$TEMP_FILE" "$TARGET"; then
  rm -f "$TEMP_FILE"
  TEMP_FILE=""
  exit 0
fi

# Atomic move
mv "$TEMP_FILE" "$TARGET"
TEMP_FILE=""

exit 0
